### ISSUE TITLE
slim application error

### ISSUE THREAD

**Issue by GNIKEI** [yfgeek/BlockVotes#3]
hi there, i m getting this error whenever im trying to open localhost, any ideas?

`Slim Application Error
The application could not run because of the following error:

Details
Type: InvalidArgumentException
Message: Unsupported driver []
File: C:\wamp64\www\vendor\illuminate\database\Connectors\ConnectionFactory.php
Line: 232
Trace
#0 C:\wamp64\www\vendor\illuminate\database\Connectors\ConnectionFactory.php(64): Illuminate\Database\Connectors\ConnectionFactory->createConnection(false, Object(Closure), false, '', Array)
#1 C:\wamp64\www\vendor\illuminate\database\Connectors\ConnectionFactory.php(49): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#2 C:\wamp64\www\vendor\illuminate\database\DatabaseManager.php(176): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'default')
#3 C:\wamp64\www\vendor\illuminate\database\DatabaseManager.php(68): Illuminate\Database\DatabaseManager->makeConnection('default')
#4 C:\wamp64\www\vendor\illuminate\database\Eloquent\Model.php(3280): Illuminate\Database\DatabaseManager->connection(NULL)
#5 C:\wamp64\www\vendor\illuminate\database\Eloquent\Model.php(3246): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#6 C:\wamp64\www\vendor\illuminate\database\Eloquent\Model.php(1873): Illuminate\Database\Eloquent\Model->getConnection()
#7 C:\wamp64\www\vendor\illuminate\database\Eloquent\Model.php(1846): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#8 C:\wamp64\www\vendor\illuminate\database\Eloquent\Model.php(1816): Illuminate\Database\Eloquent\Model->newQueryWithoutScopes()
#9 C:\wamp64\www\vendor\illuminate\database\Eloquent\Model.php(3491): Illuminate\Database\Eloquent\Model->newQuery()
#10 [internal function]: Illuminate\Database\Eloquent\Model->__call('find', Array)
#11 [internal function]: App\Models\User->find(0)
#12 C:\wamp64\www\vendor\illuminate\database\Eloquent\Model.php(3507): call_user_func_array(Array, Array)
#13 C:\wamp64\www\app\Auth\Auth.php(20): Illuminate\Database\Eloquent\Model::__callStatic('find', Array)
#14 C:\wamp64\www\app\Auth\Auth.php(20): App\Models\User::find(0)
#15 C:\wamp64\www\bootstrap\app.php(57): App\Auth\Auth->user()
#16 C:\wamp64\www\vendor\pimple\pimple\src\Pimple\Container.php(113): {closure}(Object(Slim\Container))
#17 C:\wamp64\www\vendor\slim\slim\Slim\Container.php(121): Pimple\Container->offsetGet('view')
#18 C:\wamp64\www\vendor\slim\slim\Slim\Container.php(144): Slim\Container->get('view')
#19 C:\wamp64\www\app\Middleware\CsrfViewMiddleware.php(20): Slim\Container->__get('view')
#20 [internal function]: App\Middleware\CsrfViewMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#21 C:\wamp64\www\vendor\slim\slim\Slim\DeferredCallable.php(37): call_user_func_array(Object(App\Middleware\CsrfViewMiddleware), Array)
#22 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#23 C:\wamp64\www\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(67): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#24 C:\wamp64\www\vendor\slim\csrf\src\Guard.php(162): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#25 [internal function]: Slim\Csrf\Guard->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#26 C:\wamp64\www\vendor\slim\slim\Slim\DeferredCallable.php(37): call_user_func_array(Object(Slim\Csrf\Guard), Array)
#27 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#28 C:\wamp64\www\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(67): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#29 C:\wamp64\www\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(116): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#30 C:\wamp64\www\vendor\slim\slim\Slim\App.php(337): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#31 C:\wamp64\www\vendor\slim\slim\Slim\App.php(298): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#32 C:\wamp64\www\public\index.php(5): Slim\App->run()
#33 {main}`

**Comment by twistsmyth** [comment]
this  worked for me : 

$db_host = "127.0.0.1";
$db_name = "blockvotes";
$db_user = "root";
$db_pass = "";


use Illuminate\Database\Capsule\Manager AS Capsule;

$capsule = new Capsule();
$capsule->addConnection([
  'driver'    => "mysql",
  "host"      => $db_host,
  "database"  => $db_name,
  "username"  => $db_user,
  "password"  => $db_pass,
  "charset"   => "utf8",
  "collation" => "utf8_general_ci",
  "prefix"    => ""
]);

$capsule->setAsGlobal();
$capsule->bootEloquent();

**Comment by GNIKEI** [comment]
> this worked for me :
> 
> $db_host = "127.0.0.1";
> $db_name = "blockvotes";
> $db_user = "root";
> $db_pass = "";
> 
> use Illuminate\Database\Capsule\Manager AS Capsule;
> 
> $capsule = new Capsule();
> $capsule->addConnection([
> 'driver' => "mysql",
> "host" => $db_host,
> "database" => $db_name,
> "username" => $db_user,
> "password" => $db_pass,
> "charset" => "utf8",
> "collation" => "utf8_general_ci",
> "prefix" => ""
> ]);
> 
> $capsule->setAsGlobal();
> $capsule->bootEloquent();

are you able to add voter? mine is not sending e-mail i even purchased ssl for it i thought it wasnt sending because of that.. im getting stuck at 

Please wait, sending email now

**Comment by twistsmyth** [comment]
the original structure works perfectly , using the above hack will get you in but email will not send. Do this in xampp on windows . import database file (link in readme) from http://localhost/phpmyadmin. git clone eveything to the xampp folder (i.e. c:\xampp on windows) rename .sample-env to .env and adjust settings inside .env to your database and email account settings. copy everything from public folder to htdocs folder. this is the correct structure if you are still having problems then your apache settings and/or folder permissions need work. learn https://www.slimframework.com/

**Comment by vigneshmohan10** [comment]
please tell someone how to run thiis project ??

**Comment by GNIKEI** [comment]
> please tell someone how to run thiis project ??

give me ur whatsapp or e-mail and ill help you.

**Comment by vignesh1010** [comment]
Email I'd: ishwaranmmm@gmail.com

**Comment by vignesh1010** [comment]
> Email I'd: [ishwaranmmm@gmail.com](mailto:ishwaranmmm@gmail.com)
> Whatspp:9944770366



> > please tell someone how to run thiis project ??
> 
> give me ur whatsapp or e-mail and ill help you.

+91 9944770366
Email: ishwaranmmm@gmail.com

**Comment by tanmayij** [comment]
Hey! I've been having the same slim application errors despite following the instruction. Iwas doing this on a Mac OS and have tried installing the prerequisites using homebrew but cannot get the composer running. I then tried on xampp, and this problem with the public folder not showing up on localhost has popped up and somehow I can't seem to fix it. Can I please get help from someone who was successful in running this application? I really am desperate to learn. Thank you!

**Comment by harman86** [comment]
hey tanmayij i have solved this error (slim application error).it works both on MAC OS and windows laptops or PC.this is very esy to do

**Comment by tanmayij** [comment]
> hey tanmayij i have solved this error (slim application error).it works both on MAC OS and windows laptops or PC.this is very esy to do

Hey @harman86 ! Thanks for replying! Could you please contact me at jtanmayi@gmail.com and kindly help me out with running this app? Or you could drop in your contact details and I shall get in touch. Thank you very much!

**Comment by testht06** [comment]
I m getting also this error whenever im trying to open localhost!
Please tell me how to fix this error? 
My email: testht06@yahoo.com
Thanks alot

**Comment by testht06** [comment]
> > please tell someone how to run thiis project ??
> 
> give me ur whatsapp or e-mail and ill help you.

Dear @GHIKEI,
I m getting also this error whenever im trying to run BlockVotes on localhost!
Could you tell me how to fix this error? Please.
Thank you very much.

**Comment by SELVARAJRAYAPPAN** [comment]
rselvaid@gmail.com
9597332533

**Comment by SELVARAJRAYAPPAN** [comment]
please tell how to run this project... can u help me step by step procedure.. i am beginner about this.

**Comment by imax16041998** [comment]
> > please tell someone how to run thiis project ??
> 
> give me ur whatsapp or e-mail and ill help you.

Can you help me to run this project? 
This is my email: imax16041998@gmail.com
plz contact to me

**Comment by imax16041998** [comment]
> > this worked for me :
> > $db_host = "127.0.0.1";
> > $db_name = "blockvotes";
> > $db_user = "root";
> > $db_pass = "";
> > use Illuminate\Database\Capsule\Manager AS Capsule;
> > $capsule = new Capsule();
> > $capsule->addConnection([
> > 'driver' => "mysql",
> > "host" => $db_host,
> > "database" => $db_name,
> > "username" => $db_user,
> > "password" => $db_pass,
> > "charset" => "utf8",
> > "collation" => "utf8_general_ci",
> > "prefix" => ""
> > ]);
> > $capsule->setAsGlobal();
> > $capsule->bootEloquent();
> 
> are you able to add voter? mine is not sending e-mail i even purchased ssl for it i thought it wasnt sending because of that.. im getting stuck at
> 
> Please wait, sending email now
 
Can you help me to run this project?
This is my email: imax16041998@gmail.com
plz contact to me
